.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2010-2021, Deepin Technology Co., Ltd.
.\"
.TH "DEEPIN-FCITXCONFIGTOOL-PLUGIN" "1" "2021-03-26" "deepin-fcitxconfigtool-plugin manpage"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-fcitxconfigtool-plugin \- dde-control-center fcitx config plugin.
.SH DESCRIPTION
.PP
.B deepin-fcitxconfigtool-plugin
dde-control-center fcitx config plugin.
.PP
.SH AUTHOR
.PP
.B due-im
is written by Liu Wenhao ,Chen Shijie.
.PP
This manual page was written by
.MT chenshijie@\:uniontech.com
Chen Shijie
.ME
for the Debian Project (but may be used by others).

